### ISSUE TITLE
The first imagine in a track is over exposed

### ISSUE THREAD

**Issue by ralucac-telenav** [openstreetcam/openstreetcam.org#11]
I've noticed that for the tracks I've recorded recently, the first imagine is always over-exposed. See attachment. That didn't happen in the past (see the older tracks in the "my tracks" view).
![my_tracks](https://cloud.githubusercontent.com/assets/15245281/17104547/12beeea6-528c-11e6-9b5f-c297aec3f0a0.png)

**Comment by martijnv-telenav** [comment]
@alexandrui-telenav have we seen this more often?

**Comment by mirunac-telenav** [comment]
Fixed.
