### ISSUE TITLE
No way to "edit profile" or "change settings"

### ISSUE THREAD

**Issue by jidanni** [openstreetcam/openstreetcam.org#113]
I am on my
http://openstreetcam.org/user/jidanni

I want to "edit my profile".
Well I click "profile"... but OK I am already on my profile.
The user would like to check his account settings... but it seems there are none.

**Comment by mirunac-telenav** [comment]
hey @jidanni - this is the way OSC was thought of, business wise - simplistic design and a dive-right-in approach (view, delete, edit, tag).
