### ISSUE TITLE
The URL hash link  doesn't work

### ISSUE THREAD

**Issue by Rub21** [openstreetcam/openstreetcam.org#135]
Hey, I want to share the link of the app, but  the  hash link  doesn't work, it took me to the same place all the time. 
![image](https://user-images.githubusercontent.com/1152236/29338531-3aacb892-81db-11e7-8c3d-9f1284628957.png)

http://openstreetcam.org/map/@37.72970292820225,-122.38583385944368,17z

Could you check it out, 
Thank you.

**Comment by mirunac-telenav** [comment]
It should work now. Let us know, if you have the time. 
So sorry for this late reply - we're going to allocate more resources towards Git as of this year.
