### ISSUE TITLE
recorded date is not recorded date but uploaded date.

### ISSUE THREAD

**Issue by mvexel** [openstreetcam/openstreetcam.org#152]
The 'date of recording' is in fact the date the image was uploaded.

**Comment by james2432** [comment]
I believe this is the same as: https://github.com/openstreetcam/openstreetview.org/issues/44

**Comment by alexandrui-telenav** [comment]
We have this is our backlog for months but stuff kept getting on top. We do have the timestamp in the DB so would be a matter of minutes to add that to the webpage/API, BUT: we store the unix timestamp aka UTC but not the timezone. We'll have to convert using track's coordinates to get the 'user time'. Do you guys think adding the GMT in the meantime would help?

**Comment by mvexel** [comment]
I think anything is better than showing the upload time. Sometimes there’s days or even weeks between recording and uploading for me. (This is because I don’t use the app but a dedicated camera with a large SD card.)

**Comment by bogdans-telenav** [comment]
We provide a field on each photo that is the recording date called shot_date. I will close this since it was addressed if you consider otherwise please reopen it with updated details.

**Comment by hbogner** [comment]
Not addressed, please reopen this issue until problem is fixed.
Detailed explanation in issue: https://github.com/openstreetcam/openstreetcam.org/issues/44
