### ISSUE TITLE
Userlevel decreased after resume upload of incomplete tracks?

### ISSUE THREAD

**Issue by moenk** [openstreetcam/openstreetcam.org#156]
I'm very sure I got userlevel 12 after the recent upload. But, I found out there were incomplete uploads because the buggy Python-uploader crashed several times. 
After some research I noticed have to use Python 3.5 and the option "-t 1" to avoid the script from crashing during the upload (not any big issue, but should be documented!).
I let all recent 40.000 photos resume the upload (which is handled great by the software!). Then, WTF!?, I was level 11 again. Actually this does not motivate me to close imcomplete uploads ;-)
Btw, how can I close incomplete uploads? I tried to delete them but this was not possible..

**Comment by alexandrui-telenav** [comment]
Hi there, took a look at your tracks and the points and seem consistent now. Level 12 currently, to be honest I don't have an clear explanation how can the level/points decrease, but there might be an edge case we're not aware of for incomplete uploads.

CC-ing my colleague @bogdans-telenav , he'll take a look at what you mentioned about the -t 1 option and closing uploads.

**Comment by moenk** [comment]
I was able to reproduce this issue, it's level 11 again. So for now I have two options: Either leave incomplete tracks open (will they be closed automatically one day?) or not to care about statistics (curious what will happen when my counter goes below zero). 
Better would be a properly working upload script, maybe I'll look for an older release.

**Comment by bogdans-telenav** [comment]
We have now a properly working upload script. At least this one does not skip any photos. If you encounter any new issue with the new scripts please report an issue on the upload scripts repo. I will close this issue. If you encounter a scoring issue report a new issue on this repo. Thanks.
