### ISSUE TITLE
Request blurring/deletion of image

### ISSUE THREAD

**Issue by ltog** [openstreetcam/openstreetcam.org#170]
Is there a way to request blurring or deleting an image due to privacy concerns?

**Comment by alexandrui-telenav** [comment]
No blurring request feature yet ( planned but not executed ), you can however delete photos with the website if you're the contributor.

**Comment by ltog** [comment]
Ok, thank you for your response. I'm looking forward to this feature.

This issue may be closed.

**Comment by ltog** [comment]
@mirunac-telenav , @alexandrui-telenav : Are there any news regarding the implementation of blurring requests?
