### ISSUE TITLE
Unable to rotate image.

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [openstreetcam/openstreetcam.org#171]
Error
Rotation failed!

For all my tracks https://openstreetcam.org/user/ergio

**Comment by mds08011** [comment]
I am getting the same error with multiple tracks.

**Comment by ToeBee** [comment]
Same here. And I'm not sure OpenStreetCam is correctly reading the EXIF `Orientation` tag. I have an image that was flipped upside down (180 degrees) by my GoPro. I manually changed the `Orientation` tag using exiftool. They look correct on my computer but OSC has them rotated by 90 degrees.

**Comment by mirunac-telenav** [comment]
@c-e-p-x-u-o , @mds08011 the rotation issue was fixed in the meanwhile, sorry for the late update. 
@ToeBee I can see that you created #188 regarding the EXIF tag. 
Will have to close this one and continue discussing the other matter on the new ticket.

**Comment by c-e-p-x-u-o** [comment]
Success
Rotation succeed!

Thank you!
