### ISSUE TITLE
Google authentication doesn't work

### ISSUE THREAD

**Issue by tunisiano187** [openstreetcam/openstreetcam.org#177]
Hello, i'm trying to connect with my google account on the site and i receive 
redirect_uri_mismatch
The JavaScript origin in the request, http://openstreetview.org, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/168800896551-ah62qpbosiedifncvn0ip9gqggosf80k.apps.googleusercontent.com?project=168800896551 to update the authorized JavaScript origins.

Can you help me?

**Comment by mirunac-telenav** [comment]
Hi, http://openstreetview.org is obsolete, we'll redirect all attempts to https://openstreetcam.org. Will update ticket label as soon as it's done. 

Thanks!

**Comment by mirunac-telenav** [comment]
Redirect complete. 
@tunisiano187 let me know if you encounter any more issues. 
Tx
