### ISSUE TITLE
Querying OSC data

### ISSUE THREAD

**Issue by vr00n** [openstreetcam/openstreetcam.org#178]
Hi there. Is there an easy way to query OSC data by geography?

Example. 
I want to know how many streets in Los Angeles (or some geography defined in [Nominatim](http://nominatim.openstreetmap.org)) are OSC-mapped and how recent the data is.

`select * from OSC_data where geography like 'Los Angeles%'`
would return:

| index | street name | latest_capture_date | osc_track_id(s) | geography
|--|--|--|--|--|
| 1 | California Street	 | 8/8/2018 | [1111,2222,3333] | Los Angeles, California, USA

**Comment by mirunac-telenav** [comment]
Hey @vr00n - we only store coordinates.
No street names or anything similar...

**Comment by bogdans-telenav** [comment]
@vr00n if you have the coordinates for that name it would be possible. But you need the coordinates.
