### ISSUE TITLE
Last ten uploaded tracks show no points

### ISSUE THREAD

**Issue by rich123** [openstreetcam/openstreetcam.org#179]
The last ten tracks I have uploaded have all went through their "Processing" phase, and the "Processing" tag has disappeared.  But they show no points on the web panel or in the android app.

They also do not appear on the map in the web panel (no blue lines indicating where uploaded tracks exist).

**Comment by rich123** [comment]
Android 7.1.1 - app version 2.4.0 (from google play store).

**Comment by mds08011** [comment]
I had a similar problem and got this response from the OSC team:
>“Most likely map matching issue. The underlying road network used is a pretty old version of OSM and is sometimes buggy, so there are inconsistencies. This is currently in progress to be switched to a new component that uses constantly updated maps.
>…this affects only the main OSC map ( JOSM & iD display the raw GPS track, same for the track details page which should display the tracks above ). A fix is coming soon.”

Do your GPS tracks show up in the inset map display while viewing photos?

**Comment by rich123** [comment]
> Do your GPS tracks show up in the inset map display while viewing photos?

If you mean the inset map when using the openstreetcam.org website view of the tracks, then yes.

Oddly, two of the ten tracks are in my normal "recording area" that has always had points appear, and one of them is a small, newer, recording of the same part of a street that I had previously recorded, the prior recording was assigned points, the newest one, nothing at all.

**Comment by mds08011** [comment]
Yeah, that sounds like the same situation I was having.  The inset map while viewing individual tracks shows the raw GPS, while the main openstreetcam.org homepage only shows purple lines for those that matched to the map successfully.

**Comment by i5513** [comment]
I have the same problem with my two last tracks [1] (I reported it from the app, but not sure where is the report)

I have configured all by default (mp4)

Saludos
[1]  https://openstreetcam.org/details/1320215/64/track-info
https://openstreetcam.org/details/1320207/0/track-info

**Comment by mds08011** [comment]
@i5513 This seems to be a recent issue affecting all OSC tracks uploaded since December 21, 2018.  See: #200

**Comment by mds08011** [comment]
@i5513 It looks like your issue should be resolved now.

https://github.com/openstreetcam/openstreetcam.org/issues/200#issuecomment-451181506
>There was a glitch in the points system that we didn't catch during the holiday break, sorry folks. Points are back up and should be retro-actively assigned to your uploads.

**Comment by i5513** [comment]
Thank you very much! Yes It fixed the problem!

**Comment by mirunac-telenav** [comment]
@i5513, @rich123 - points calculation is up and running on our end now, can you please confirm if it's ok to close this issue?

**Comment by i5513** [comment]
> @i5513, @rich123 - points calculation is up and running on our end now, can you please confirm if it's ok to close this issue?

Yes, for me, you can close the bug, thank you !

**Comment by rich123** [comment]
Yes, it looks like all the tracks now have a points value attached.  So it looks ok to close the issue.

**Comment by panthersdude2001** [comment]
Openstreetcam is showing up sequences with no points whatsoever.
Running android - G550T with version 2.9.0. Points are turned on, but no points shown.
![no points](https://user-images.githubusercontent.com/44646536/62825120-b479ea80-bb74-11e9-8618-54013322b141.png)

**Comment by panthersdude2001** [comment]
Nevermind, sequences still processing. Not complete yet with upload. Duh!

**Comment by panthersdude2001** [comment]
Please reopen this, as #231 is still causing issue, even for other users.
#230 for more info. Last comment.
