### ISSUE TITLE
mp4 vs. jpg capture

### ISSUE THREAD

**Issue by kreuzschnabel** [openstreetcam/openstreetcam.org#182]
Hi, I set OSC on my phone to record in JPEG mode instead of mp4. Capturing is way smoother that way – mp4 mode keeps to pause capturing from time to time in order to process the images taken which does not happen in JPEG mode. However, tracks shot in JPEG mode seem to be treated as second class footage by the project: 

1. I do not score any points for JPEG tracks uploaded. Though it is not my primary goal to climb the top of the leaderboard, this confuses me, since the score being displayed during shooting. 

2. Uploaded tracks shot in JPEG mode do not show up on the coverage map. At least mine don’t, though they cover otherwise uncovered roads (see tracks #1292873, #1292133 and so on). 

Question is, why does the project obviously disencourage users from capturing in JPEG mode, in spite of their better coverage (because of more continuous shooting) and – IMHO – better image quality? 

--ks

**Comment by mds08011** [comment]
It sounds like this might actually be a result of a map-matching error rather than being a result of your use of JPEGs.  See this similar issue:  https://github.com/openstreetcam/openstreetcam.org/issues/179 

Have you tried switching back to MP4 to see if the same issue occurs?

**Comment by alexandrui-telenav** [comment]
Looking at http://openstreetcam.org/user/kreuzschnabel it does seem like a few tracks don't have points. We don't intentionally discriminate JPEG-mode photos, any problem is considered a bug. We'll look into that in the next few days ( added this to the team's sprint ).
Thanks for reporting

**Comment by mirunac-telenav** [comment]
@kreuzschnabel - it should be ok now, checked your profile as well, all trips have points assigned. Can you confirm?
