### ISSUE TITLE
image is shown unrotated after succesfull rotation

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [openstreetcam/openstreetcam.org#189]
I press Rotate image -> Save -> Success, Rotation succeed!
But now I need to reload the page with Ctrl-R to see rotated image.

**Comment by mirunac-telenav** [comment]
By design - not a bug. 
Will probably refine the structure entirely, but that's probably a task for next year.

**Comment by c-e-p-x-u-o** [comment]
It's a bug. Please leave it open.

**Comment by c-e-p-x-u-o** [comment]
Just add page before alerting "Success, Rotation succeed!"
