### ISSUE TITLE
What does search button?

### ISSUE THREAD

**Issue by 532910** [openstreetcam/openstreetcam.org#194]
It's absolutely unclean what the search button in the bottom right corner does.

![image](https://user-images.githubusercontent.com/14617699/49666890-70c16500-fa6a-11e8-969a-4d461cddc0e0.png)

**Comment by mds08011** [comment]
It automatically zooms in on the sign detections as you scroll through images.

It was mentioned in this blog post: http://blog.improveosm.org/en/2018/11/help-train-openstreetcams-open-sign-detection-platform/

>Next to the trip slider, underneath the image, you will find a small magnifying glass button. Clicking this will automatically zoom and pan the image to the detection.

**Comment by c-e-p-x-u-o** [comment]
The icon is OK. Could you add onmouseover float popup with "sign detection" or something like this?

![onmouseover](https://user-images.githubusercontent.com/14617699/49829756-4c35f780-fda0-11e8-9dbd-58a43f645975.png)

**Comment by paulk-telenav** [comment]
Added tooltip on button, zoom buttons will be shown only when the current photo has detections mapped.
