### ISSUE TITLE
Portion of multiple tracks not shown on map

### ISSUE THREAD

**Issue by ithink314** [openstreetcam/openstreetcam.org#197]
Processed tracks show route over Veterans Road/bridge, but map shows no "purple" track line for that portion. Maybe the issue is mapping when too many tracks go over the same route.

![screenshot_2018-12-12_13-40-14](https://user-images.githubusercontent.com/843769/49891434-7fb26980-fe14-11e8-861f-d87cd27ac2ce.png)
![screenshot_2018-12-12_13-42-09](https://user-images.githubusercontent.com/843769/49891442-83de8700-fe14-11e8-9285-339d64431937.png)

**Comment by mds08011** [comment]
This is likely related to "map matching".  I had a similar problem and got this response from the OSC team:
>“Most likely map matching issue. The underlying road network used is a pretty old version of OSM and is sometimes buggy, so there are inconsistencies. This is currently in progress to be switched to a new component that uses constantly updated maps.
>…this affects only the main OSC map ( JOSM & iD display the raw GPS track, same for the track details page which should display the tracks above ). A fix is coming soon.”

https://github.com/openstreetcam/openstreetcam.org/issues/179#issuecomment-429419328

**Comment by ithink314** [comment]
In this case the bridge is relatively newly constructed, in the last couple years, so "old and buggy" excuse should not really apply.

**Comment by ithink314** [comment]
@mds08011  I've just wasted several minutes confirming, as you said, the OSC "main" map display is out of date compared with OSM, when looking at a "gap" displayed in a recent track/trace. To make it worse, the track actually shows travel on a road (30 foot street) that was NOT traversed. Oddly, the small OSC "photo review" map seems to be more up to date than the main map. 

To me this glitch discourages planning alternative routes to destinations, because the "main" map display may or not actually show where tracks have already been recorded. Also, in the attached screenshots, the OSC map implied editing was needed to show a missing road; however, OSM already has the road, so no editing was really needed. This glitch then also discourages reviewing tracks to look for needed edits. Sigh.

![screenshot_2019-01-18_13-02-41](https://user-images.githubusercontent.com/843769/51404832-9db16f00-1b22-11e9-8003-25fda695ee49.png)
![screenshot_2019-01-18_13-03-26](https://user-images.githubusercontent.com/843769/51404833-9db16f00-1b22-11e9-8fe9-21db16589b7f.png)

**Comment by mds08011** [comment]
While certainly not as convenient as being able to check the OSC app, a potential workaround could be to use the OSM "Edit" function with photos overlaid.  This would give you the most up-to-date map with true GPS locations.

![image](https://user-images.githubusercontent.com/8010709/51408399-68515500-1b13-11e9-81bd-7ba0a6f9bbeb.png)

**Comment by ithink314** [comment]
@mds08011 I appreciate the suggestion, but the blue color tracks/traces in ID are only clearly visible for me at higher zooms. Below somewhere around 12 or 13, they just blend into the background. Plus, I seem to need a newer/better PC with faster graphics to get reasonable speed screen updates in ID. I haven't found a statement of minimum hardware requirements, but my laptop seems below it!

**Comment by joeybab3** [comment]
I can confirm that even on the map where there is a road, sections are missing on the openstreetcam map though not on the openstreetmap display.

**Comment by cliffordsnow** [comment]
Is it possible to get a fix on this item? I'm working on mapping sidewalks and crosswalks in [La Conner, WA](https://www.openstreetmap.org/relation/237861). Having an updated map would aid in figuring out what areas I either haven't uploaded or haven't driven.  Thanks in advance

**Comment by alexandrui-telenav** [comment]
Hi all, the coverage map has been updated with an improved map matcher and fresh map.
The initial problem of this thread seem to be resolved. 

<img width="902" alt="Screen Shot 2019-05-09 at 1 51 16 PM" src="https://user-images.githubusercontent.com/17335176/57448239-8b8a4680-7261-11e9-9df2-1e0e00557942.png">

**Comment by alexandrui-telenav** [comment]
@cliffordsnow , do you refer on the map tiles or the purple coverage not being accurate?
The initial problem refers to the coverage part and want to make sure we're referring to the same thing.

**Comment by ithink314** [comment]
I would not close this issue. The 2nd example I provided still exists, and another slightly to east of that one still exists; both are from OSC tracks and OSM map updates made around the time this issue was opened (I.e old enough they should be fixed).

**Comment by cliffordsnow** [comment]
Sorry for not being more specific. I was referring to the purple coverage. I've been capturing this area, https://openstreetcam.org/map/@48.3885201817806,-122.4934494495392,16z with the goal of being able to map all sidewalks, crosswalks and curb cuts in the city. I started uploading on May 5th.
