### ISSUE TITLE
Points are not updating, leaderboards are empty

### ISSUE THREAD

**Issue by pkoby** [openstreetcam/openstreetcam.org#200]
I mentioned this issue in a [closed thread](https://github.com/openstreetcam/openstreetcam.org/issues/168#issuecomment-449851998) a few days ago, but I think this is actually a different problem.

My sequences uploaded since Friday the 21st are having no points calculated. Checking other users' profiles, this seems to be the case for everyone. Also, the leaderboards for daily and weekly are empty because of this.

**Comment by mds08011** [comment]
I am experiencing the same issue and it appears to be affecting all the other accounts/profiles I’ve seen.

**Comment by ithink314** [comment]
Ditto. Of course it happened during holidays...

**Comment by Approksimator** [comment]
No daily, no weekly, no monthly leaderboard. No data was found! Reload or go Back

**Comment by bbbulsara** [comment]
Yes, No updates after 27th Dec, every time it upload, it show's nothing, uploaded almost 4-5 new route.

**Comment by pkoby** [comment]
I suddenly have points again, and all the leaderboards seem up-to-date!

**Comment by mvexel** [comment]
There was a glitch in the points system that we didn't catch during the holiday break, sorry folks. Points are back up and should be retro-actively assigned to your uploads.

I will leave this issue open in case you still experience issues with the leaderboards @Approksimator @pkoby ?

**Comment by Approksimator** [comment]
Everything is ok! Closed!

**Comment by pkoby** [comment]
All good, thanks!
