### ISSUE TITLE
Many thumbnails not showing for "Nearby Tracks" in map view

### ISSUE THREAD

**Issue by pkoby** [openstreetcam/openstreetcam.org#202]
When I click on the map, the page pops up a list of Nearby Tracks at the bottom. There should be thumbnails of the image at the point clicked, and sometimes this works. However, for many places, I am not seeing any image, just a black (checkered) rectangle.

Clicking around the map, I'm finding that the ones that do show thumbnails don't have a specific camera association, but Waylens seems to show up more often than not. Also, the thumbnail URLs that don't show seem to be in the storage1 or storage8 areas of the OSC file system. The ones that show up seem to be in other numbers.

It would really be nice to see all thumbnails for every sequence/image to help orient where you're looking at.

**Comment by mirunac-telenav** [comment]
hey @pkoby - 'nearby tracks' went through a series of improvements. It should be working now. Can you please check and confirm?

**Comment by pkoby** [comment]
Yes, I have noticed it has worked for a little while now. Thanks!
