### ISSUE TITLE
iPhone OSC app - alternative landscape view

### ISSUE THREAD

**Issue by steerage250** [openstreetcam/openstreetcam.org#203]
The iPhone OSC app only allows one (landscape) view - with the camera in the top left corner.  For my right-hand drive car, this means I cannot use it on the driver's side next to the rear-view mirror, because the car has some tinting on the glass around the mirror.  (and it is too intrusive to have in the top right corner of the windscreen).

When I have it at the top of the windscreen anywhere left of the rear-view mirror, the windscreen wiper doesn't wipe in front of the camera.

Why can't the app allow the "other landscape view" (with the camera in the bottom right of the phone - facing forward towards the bonnet)?

**Comment by ciprianh-telenav** [comment]
@steerage250, version 2.6.1, now available on AppStore, brings support for both landscape orientations. 👍

**Comment by steerage250** [comment]
terrific - thank you
