### ISSUE TITLE
Error: "Cannot load image from server. Might be CORS related."

### ISSUE THREAD

**Issue by mds08011** [openstreetcam/openstreetcam.org#204]
While trying to view someone else's track, I got an error message I haven't seen before: "Cannot load image from server. Might be CORS related."

It appears to be related to this specific track, as all others I viewed worked without error.  Track in question: https://openstreetcam.org/details/1122436/

![image](https://user-images.githubusercontent.com/8010709/52240800-ca85b600-2886-11e9-8f6d-1e2bbcf6cb21.png)

**Comment by alexandrui-telenav** [comment]
Hey Malcom, we had a temporary problem with one of the storage servers. Back online now.
We're in the process of migrating data to a distributed filesystem to avoid this in the future.

**Comment by mds08011** [comment]
Thanks!

**Comment by RafalR** [comment]
This is probably not a temporary problem... Today, yesterday... - "Cannot load image from server. Might be CORS related." - https://openstreetcam.org/details/1168953/0/track-info

**Comment by panthersdude2001** [comment]
#244

**Comment by panthersdude2001** [comment]
Must be down, because we are still getting this error.

**Comment by GeekOnTheHill** [comment]
About half of the sequences I've uploaded get that error during processing. Also, none of those sequences have successfully finished processing, and the thumbnail in the tile doesn't show up. Just blank boxes. 

They do have the number of images, kilometres, and so forth in the caption; but not the thumbnail images.
