### ISSUE TITLE
Sequence summary shows 0 photos, 620 visible in viewer

### ISSUE THREAD

**Issue by jonnoct** [openstreetcam/openstreetcam.org#206]
There are a few problems with the following track...

https://openstreetcam.org/details/1340547/5/track-info

1.  It is not linked to my profile page
2.  Track Info shows "0 Photos".  Viewer shows 620 photos and no issues viewing the first few photos.
<img width="1435" alt="screen shot 2019-02-14 at 2 06 15 pm" src="https://user-images.githubusercontent.com/19223920/52810918-bd747e00-3061-11e9-89c7-7ca2a0c9c356.png">

**Comment by jonnoct** [comment]
No sequences I've uploaded after this one have been linked to my account (possibly same issue?).  I am getting the points for them and they're showing in the map so I don't think the data's been lost.

**Comment by bogdans-telenav** [comment]
I just saw that there is an issue with the processing of this sequence. The sequence is assigned to you, all the data was uploaded but for some reason it appears to be stuck in some processing state. Maybe it is something wrong with the processing of the sequences . We will investigate tomorrow and come back with an update until then, please postpone any other upload.
