### ISSUE TITLE
remote control is not a plugin

### ISSUE THREAD

**Issue by mvexel** [openstreetcam/openstreetcam.org#208]
![image](https://user-images.githubusercontent.com/120452/53441016-1e397a00-39c3-11e9-8ae0-447091a7fd87.png)

The Remote Control functionality is not a plugin, but [exists in core JOSM](https://wiki.openstreetmap.org/wiki/JOSM/RemoteControl). Please update the dialog text.

**Comment by paulk-telenav** [comment]
Done
