### ISSUE TITLE
Create new image 

### ISSUE THREAD

**Issue by Flightlessballer** [openstreetcam/openstreetcam.org#209]
Is there a funtion in OSM to add undetected signs?

**Comment by mds08011** [comment]
See https://github.com/openstreetcam/openstreetcam.org/issues/163#issuecomment-397597351:
>It's possible to do that on beta.openstreetcam.org. We didn't make that very public as we're still thinking about some moderation steps in case of vandalism. Please play nice :)

**Comment by mirunac-telenav** [comment]
Thanks @mds08011!
@Flightlessballer is it ok to close this ticket?
