### ISSUE TITLE
Sign review

### ISSUE THREAD

**Issue by topmagis** [openstreetcam/openstreetcam.org#210]
It would be helpful when reviewing signs if the display zoomed in to the selected sign close enough to see if it was correctly identified or not.

**Comment by mds08011** [comment]
You can accomplish this by clicking the magnifying glass icon at the bottom right corner of the image.

This feature is discussed in this blog post: http://blog.improveosm.org/en/2018/11/help-train-openstreetcams-open-sign-detection-platform/
>Next to the trip slider, underneath the image, you will find a small magnifying glass button. Clicking this will automatically zoom and pan the image to the detection.

Similar discussion: #194

**Comment by topmagis** [comment]
Excellent! That helps me a lot.
Perhaps this should be ‘ON’ by default?

George Dunbar
GIS Coordinator
26 Court Street
Plymouth, MA 02360
508-747-1620  x10212
https://www.plymouth-ma.gov/gis

**Comment by mirunac-telenav** [comment]
Thanks @mds08011 
@topmagis is it ok to close this ticket?

**Comment by topmagis** [comment]
Yes, thank you for pointing out that this functionality is already built into the system.
