### ISSUE TITLE
"My Tracks" doesn't do anything anymore?

### ISSUE THREAD

**Issue by joeybab3** [openstreetcam/openstreetcam.org#220]
On the website clicking the checkbox for "my tracks" no longer shows just my tracks?

**Comment by mds08011** [comment]
My tracks got a big refresh:

![image](https://user-images.githubusercontent.com/8010709/61923112-a3e03800-af17-11e9-90b3-84667803d0eb.png)

**Comment by mirunac-telenav** [comment]
@mds08011 - mhm 👍 
it's also working properly now!
sorry we didn't come back sooner to this issue with an answer
