### ISSUE TITLE
10 point per image no longer received once processed?

### ISSUE THREAD

**Issue by joeybab3** [openstreetcam/openstreetcam.org#221]
I have not been getting the 10 point images anymore for a bit now, and so to test that I went to an area where there was a long stretch of no images:
https://openstreetcam.org/details/1380922/1168/track-info
The max I was able to get was the 5 point per image bonus.

If this is by design and the 10 point value is going away, I suggest you have the app no longer display "10x" for new roads?

**Comment by alexandrui-telenav** [comment]
10 points/image is still in place, might be related to a recent delay in showing new tracks on the map but points calculation didn't change. We'll double check.

**Comment by rwelty1889** [comment]
10 points per image appears to work now for new track uploads, but the ones that didn't get it have not been updated. and purple track display for new uploads seems broken again.

**Comment by britiger** [comment]
Hi, i also upload my images see https://openstreetcam.org/details/1455458 and https://openstreetcam.org/details/1454522 but i didn't get 10 points for New Road, it always show Coverage=1 with 5 points. On some roads it's correct but most were mapped so fare. May it's a problem with the distance between the images I made? i've configured 1 image per 30m. 
Only https://openstreetcam.org/details/1455246 have 10 points/image but seams to be stuck in processing state.

**Comment by joeybab3** [comment]
I can confirm I am still getting incorrect point values

**Comment by synalik** [comment]
Hi, two days ago I received only 1 point for mapping brand new roads:
https://openstreetcam.org/details/1517050/0/track-info
https://openstreetcam.org/details/1517106/0/track-info
Sometimes (very few times in past 1 month) I got 10 points per picture, even the road is first time mapped.

**Comment by joeybab3** [comment]
The tracks never successfully processed but there are many more pressing issues and new tracks no longer have these issues.
