### ISSUE TITLE
Recording disappeared

### ISSUE THREAD

**Issue by mvexel** [openstreetcam/openstreetcam.org#230]
I just uploaded 1.5 hours of driving just to have it disappear! It's not on my profile and I have no tracks 'processing' or 'uploading'.

Where are my photos?

**Comment by panthersdude2001** [comment]
Same here.
Solution: If you have a SD card when using OSC, follow the steps below.
Disconnect the SD Card from the phone and insert it into computer with SD Card adapter.
After that, it may say there's a problem with this drive. Click on the toast notification and click Scan and Fix (first option). After that, it should say it found errors. Click on repair now. Wait a few moments. It should say this
"Your drive has been repaired. The drive is ready to use"
If you do not see the toast, right click on your sd card and click settings. Click on the tools tab and click check for errors. Follow the steps above, and if it says the repair success message, that means there is a problem with the SD Card itself.
I had the same problem with OSC deleting mutliple sequences from SD Card, by renaming the android folder to a file of the same name. 
You can use a recovery system to recover the images, the Gzip file, and the text file, by using the RecoverMyFiles software.

**Comment by mvexel** [comment]
My recording now appeared after a day. But my account didn't have any 'uploading' or 'processing' tracks which made me believe that it had disappeared altogether. Now the track does appear but no points (yet).

https://openstreetcam.org/details/1936945/0/track-info

**Comment by panthersdude2001** [comment]
#231

**Comment by panthersdude2001** [comment]
This problem still persists today, all sequences taken after September 28 2019 was destroyed. not sure what happened. 😕
