### ISSUE TITLE
uploaded track disappears

### ISSUE THREAD

**Issue by rwelty1889** [openstreetcam/openstreetcam.org#235]
using the phone app because i left my GoPro behind, took a track, uploaded, and it does not show up anywhere on openstreetmap.org

**Comment by klg113** [comment]
Experienced the same thing recently, uploaded a number of tracks via Android app, at which stage they were automatically deleted from device but still not showing up on openstreetcam.org 2 days later.

**Comment by rwelty1889** [comment]
my track finally showed up too, so it's just really, really slow

**Comment by alexandrui-telenav** [comment]
We had a downtime recently on the face & license plate detection component and a processing queue built up quickly.. 
Cleared the queue in the meantime and new tracks should appear significantly faster.
Sorry about that!
