### ISSUE TITLE
Allow import of own photos from Mapillary

### ISSUE THREAD

**Issue by 12people** [openstreetcam/openstreetcam.org#240]
Mapillary allows a user to export all of his photos. It'd be nice if one could then upload those photos to OpenStreetCam, thereby being able to contribute to both services at the same time.

**Comment by mds08011** [comment]
As long as the photos have locations associated with them (EXIF data) you may be able to upload to OSC with the python upload scripts: https://github.com/openstreetcam/upload-scripts

**Comment by panthersdude2001** [comment]
@12people see #257 for info on the comeback of mapillary
![image](https://user-images.githubusercontent.com/44646536/85060423-3cf0f080-b173-11ea-9dd0-4a3b9184f500.png)
