### ISSUE TITLE
❌ Cannot delete partially uploaded track

### ISSUE THREAD

**Issue by minty** [openstreetcam/openstreetcam.org#241]
Hi,

I have a _partially_ uploaded openstreetcam track that I would like to delete, but the website throws an error if I try to delete the track or the images within it.

https://openstreetcam.org/details/2027393/

I'm uploading images via `upload-scripts/osc_tools.py` and ctrl-C'd out when I realised it was uploading the wrong images. Thus the track is a "partial" upload and I suspect my issue is related to the fact that the track-upload did not fully "complete".

If I try to delete an image from the track, the error returned is:

> Photo cannot be deleted! 400 - Bad Request - 671: The status is incorrect. The sequence of the photo you are tring to access is in processing.

If I try to delete the track instead (which is really my goal), it returns:

> There was a problem deleting sequence!

How can I delete this track?

[update] likely dupe of (unanswered) https://github.com/openstreetcam/openstreetcam.org/issues/224
Thanks!

**Comment by mds08011** [comment]
I think your best bet is the workaround mentioned here: https://github.com/openstreetcam/upload-scripts/issues/83

**Comment by minty** [comment]
Thanks for the pointer @mds08011 👍 

Things appear to have evolved slightly since the link you mentioned was written. I have no `count_file.txt` and `sequence_file.txt` files.

I'm currently running:

```
commit 600c3d4f90970d675490a3a398ec66ded201b9d4 (HEAD -> master, origin/master, origin/HEAD)
Author: Bogdan I. Sala <bogdans@bogdans-nmbp.local>
Date:   Wed Feb 27 17:34:15 2019 +0200
```

## What I did

1. Took another (totally different) dashcam video & generated all the images like I was going to upload it.
2. Rather than simply upload it as normal, running `python3.7 upload-scripts/osc_tools.py upload -p SOME_DIR_WITH_IMAGES`, instead ...
3. I manually created `osc_sequence_id.txt` inside `SOME_DIR_WITH_IMAGES` and put into that file `{"id": "2027393"}` where that `2027393` is the one for the track that was stuck in the *uploading* state.
4. Then I ran `python3.7 upload-scripts/osc_tools.py upload -p SOME_DIR_WITH_IMAGES`

As I understand it, `osc_sequence_id.txt` would normally get created & populated automatically by the `osc_tools.py` script. However, because I created it by hand, the script assumed that was the track and uploaded images to that track ID i had put into that file.

My broken track previously had 121 images and was showing in state *Uploading*

After doing the above, which claimed to upload 121 images again to that track ... I still only have 121 images in the track and they appear to be the original 121 images, so I'm not sure where the new 121 images have ended up ... but the broken track is now in state *Processing*.

I still cannot delete it or images within it, but hopefully once it's finished processing I will be able to.

**Comment by minty** [comment]
Now my track is stuck in state *Processing* (for the last 2 hours), which also prevents it being deleted.

:/

**Comment by mds08011** [comment]
I'd give it a bit more time to finish processing (couple days), but I'm out of ideas if it doesn't.

**Comment by minty** [comment]
Track is still saying "processing" after 25 days, still cannot be deleted.

Cannot delete the track, or the images within the track.

Is there any way to reach someone who runs the OSC service for help? 

Is my only option to delete my entire account & all the tracks I've uploaded?

**Comment by minty** [comment]
Finally managed to reach someone via hello@openstreetcam.org

they managed to fix the track sufficiently that I was able to delete it

thanks for all the help & assistance
