### ISSUE TITLE
Cannot upload sequences [ lost photos]

### ISSUE THREAD

**Issue by james2432** [openstreetcam/openstreetcam.org#243]
As detailed in:
https://github.com/openstreetcam/android/issues/156

There is a conversion error in the logs to a boolean type and lost all the pictures I uploaded

Here is log:

[log_10_10_06_21.txt](https://github.com/openstreetcam/openstreetcam.org/files/3714879/log_10_10_06_21.txt)

**Comment by panthersdude2001** [comment]
Why close this?

**Comment by james2432** [comment]
Photos showed up, could have been due to infrastructure change

**Comment by panthersdude2001** [comment]
But I am still having the problem, Cannot load image from server. Might be CORS related. Are you having this error?

**Comment by panthersdude2001** [comment]
Ok. Thanks, will check to make sure it works now.

**Comment by panthersdude2001** [comment]
![error](https://user-images.githubusercontent.com/44646536/66650180-f7e8e780-ebfd-11e9-94a1-bff9b331f659.png)
Still giving me the error.

**Comment by james2432** [comment]
my problem was they werent even showing up in my profile at all. now that they are there, my issue is a non-issue. yours seems different
