### ISSUE TITLE
Cannot load image from server. Might be CORS related.

### ISSUE THREAD

**Issue by panthersdude2001** [openstreetcam/openstreetcam.org#244]
When uploading images to server, it gives me the above message.
Please fix this.

**Comment by panthersdude2001** [comment]
@alexandrui-telenav or anybody in the telenav group, can somebody tell me what the problem is?

**Comment by panthersdude2001** [comment]
@mirunac-telenav @bogdans-telenav @smarandal-telenav @alexandrui-telenav 
Anybody willing to solve the problem? Still giving me the error.

**Comment by bogdans-telenav** [comment]
There was a lot of work with the infrastructure lately and a lot of issues were found and fixed. We will try to investigate your problem next week but for a starting point please provide us with the links that are having this error and/ or steps to reproduce. You uploaded images with scripts, iOS, Android or Waylens?

**Comment by panthersdude2001** [comment]
Android is the uploader.
https://openstreetcam.org/details/1961581
Try going to any of my captures using https://openstreetcam.org/user/snowcool776 or https://openstreetcam.org/user/computer-geek

**Comment by bogdans-telenav** [comment]
@panthersdude2001 now it should work. Please confirm.

**Comment by panthersdude2001** [comment]
![yes!](https://user-images.githubusercontent.com/44646536/66760627-7fd62800-ee70-11e9-8c0a-c37f3ccb6eba.png)
Works! Thanks for the fix! Closing issue.

**Comment by panthersdude2001** [comment]
Reopening issue as problem persists.

**Comment by panthersdude2001** [comment]
fixed now, closing.
