### ISSUE TITLE
Openstreetcam Sequence processing

### ISSUE THREAD

**Issue by SAMI-ZAMAN** [openstreetcam/openstreetcam.org#251]
Uploaded sequences 2 days ago and they are still under processing status. Can anyone help me out with it.

https://openstreetcam.org/details/2085310
https://openstreetcam.org/details/2085306
https://openstreetcam.org/details/2085294
https://openstreetcam.org/details/2085286
https://openstreetcam.org/details/2085290
https://openstreetcam.org/details/2085302
https://openstreetcam.org/details/2085314
https://openstreetcam.org/details/2085318
https://openstreetcam.org/details/2085322
https://openstreetcam.org/details/2085282

![osc](https://user-images.githubusercontent.com/61782979/75873557-1910d580-5e36-11ea-9ac6-7c8ac00d7153.png)

**Comment by rwelty1889** [comment]
i'm seeing same

**Comment by siliconninja** [comment]
Thanks for reporting. I checked today and the issue was fixed. See also issue #250.

**Comment by siliconninja** [comment]
Update from a member on the OSC team:
https://reddit.com/r/openstreetmap/comments/fckp8j/_/fjjlkg1/?context=1

**Comment by SAMI-ZAMAN** [comment]
Thanks @siliconninja  for responding as well as briefing about the transition.
