### ISSUE TITLE
Tracks now starting to return from unavailability, but some not shown still.

### ISSUE THREAD

**Issue by panthersdude2001** [openstreetcam/openstreetcam.org#253]
@chip-grab when trying to view sequences, almost every single one of them disappeared. Also, I'm down to a level 6, not 11. What is going on here?

**Comment by panthersdude2001** [comment]
oh wait, i saw something to the bottom of the website.
10 Apr 2020, 10:00 GMT
Some sequences might be unavailable due to a technical issue.
We are working on the fix.

**Comment by panthersdude2001** [comment]
and that is the problem.

**Comment by chip-grab** [comment]
@panthersdude2001, yes, there is a technical issue that affects the visibility of some of the last sequences. We are working on the fix. We expect to have everything back to normal in a matter of few days. Thank you for your patience.

**Comment by panthersdude2001** [comment]
oh ok, thanks chip! will be checking!

**Comment by panthersdude2001** [comment]
can we still upload new sequences during this glitch?

**Comment by chip-grab** [comment]
Yes, new sequences should be visible.

**Comment by chip-grab** [comment]
@panthersdude2001, here is a quick update on the glitch: 1,669 of the 13,714 sequences affected are now back active. 🤞

**Comment by panthersdude2001** [comment]
Yay! Thanks Chip!

**Comment by chip-grab** [comment]
5,010 / 13,714 re-activated

**Comment by panthersdude2001** [comment]
thanks!

**Comment by panthersdude2001** [comment]
What is the status on the reactivation @chip-grab?

**Comment by panthersdude2001** [comment]
THANK YOU SO MUCH @CHIP-GRAB FOR RESTORING EVERY SINGLE TRACK BACK TO NORMAL! CLOSING.
