### ISSUE TITLE
Lots of tracks not processing

### ISSUE THREAD

**Issue by joeybab3** [openstreetcam/openstreetcam.org#254]
I have something like 15 tracks that have 0 points so I assume they are not processing. Every time I file an issue on here they are usually fixed within a month but no one ever responds. Is there any way to file tracks to be reprocessed so that I don't have to open an issue every time?

These happened before this most recent outage as well.

**Comment by joeybab3** [comment]
Some of the tracks:
https://openstreetcam.org/details/2108950
https://openstreetcam.org/details/2108650
https://openstreetcam.org/details/2108362
https://openstreetcam.org/details/2108354
https://openstreetcam.org/details/2108350
https://openstreetcam.org/details/2108346
https://openstreetcam.org/details/2108342
https://openstreetcam.org/details/2105678
https://openstreetcam.org/details/2105658
https://openstreetcam.org/details/2087702
https://openstreetcam.org/details/2087698
https://openstreetcam.org/details/2087694
https://openstreetcam.org/details/2081682
https://openstreetcam.org/details/2079314
https://openstreetcam.org/details/2073002
https://openstreetcam.org/details/2066486
https://openstreetcam.org/details/2052438
https://openstreetcam.org/details/1928285

and then there's this one...
https://openstreetcam.org/details/2034638/

**Comment by flohoff** [comment]
I have the same issues. Although the number of tracks processing shows "0" i have approx 20K images in 8 sequences in processing state.

Just 2 examples - Oldest not processed is from the 28th of April. Newest one is from the 13th of June.

https://openstreetcam.org/details/2385902/0/track-info
https://openstreetcam.org/details/2383394/0/track-info

Also i have a track stuck in uploading although the uploading script is finished.

Flo

**Comment by flohoff** [comment]
While at it: Since beginning of June the reverse geocoding and thus naming of tracks/sequences does not work anymore.

Flo

**Comment by joeybab3** [comment]
> While at it: Since beginning of June the reverse geocoding and thus naming of tracks/sequences does not work anymore.
> 
> Flo

I noticed that, I’m hopeful that it’s caused by them doing work on the backend to fix some of these bugs but as you can probably see most of my issues on here and elsewhere don’t get responses.

**Comment by flohoff** [comment]
From my perspectived the whole project looks pretty dead. I had a hard time finding ANY way to communicate. I am happy with github issues but you wont find it on the website anywhere. The twitter account is dead for a year now and it seems most of the operations on the repositories has ceased in December oder January.

Flo

**Comment by joeybab3** [comment]
@flohoff I've noticed that as well, and that's something I brought up on r/openstreetmap. 
I like contributing to this project but increasingly there isn't a point, currently some tracks process, some don't and if they don't you're essentially out of luck. I film data and it uploads and then never shows up in my account and no one on this project seems to be actively working on it anymore.

I posted about this at https://www.reddit.com/r/openstreetmap/comments/fckp8j/openstreetcam/
and got a response that they're just working on the backend but that apparently was not the case.

**Comment by joeybab3** [comment]
@chip-grab seems to be the only one left responding, any words of wisdom for us?

**Comment by joeybab3** [comment]
@chip-grab Thank you for the update, I was wondering what the issue was, I still have some new tracks that got stuck in processing from a few days ago but later tracks have gotten back to processing. 

You guys should utilize your twitter account again, I think it would help to avoid confusion.

**Comment by panthersdude2001** [comment]
Agree with everyone. No sequences since Monday. All my 9 sequences i took is processing still

**Comment by panthersdude2001** [comment]
Here we go! Thanks @chip-grab for the info!
![image](https://user-images.githubusercontent.com/44646536/85056459-437c6980-b16d-11ea-9d6d-13d48b2f2f61.png)

**Comment by panthersdude2001** [comment]
Also, is anybody gonna work on the no street address thingy at the bottom? Mapillary has this. Could this be a part of metadata 2.0?

**Comment by joeybab3** [comment]
> Agree with everyone. No sequences since Monday. All my 9 sequences i took is processing still

New tracks I've uploaded are processed but some tracks that I uploaded a week ago are stuck in processing. 

It sounds like we are stuck with this sort of patchy service until they finish refactoring @panthersdude2001 .

**Comment by panthersdude2001** [comment]
Crap! Now we have to wait.

**Comment by matkoniecz** [comment]
Once this is fixed https://wiki.openstreetmap.org/w/index.php?title=OpenStreetCam&diff=2002141&oldid=1997111 should be reverted

**Comment by panthersdude2001** [comment]
@chip-grab proccessed tracks include https://openstreetcam.org/details/2372866/0/track-info
https://openstreetcam.org/details/2372874/0/track-info
https://openstreetcam.org/details/2386106

**Comment by panthersdude2001** [comment]
So looks like points are assigned, and system is working.

**Comment by joeybab3** [comment]
@panthersdude2001 for now... I still have 5 tracks that are stuck in processing.

**Comment by panthersdude2001** [comment]
And also, why is the rankings now up to 200 instead of 50?

**Comment by joeybab3** [comment]
@panthersdude2001 Not sure what you're referring to, I haven't noticed anything different with the rankings?

**Comment by panthersdude2001** [comment]
Notice this @joeybab3 
![image](https://user-images.githubusercontent.com/44646536/85157248-3a50d280-b229-11ea-88c6-52b809a0b354.png)

**Comment by joeybab3** [comment]
Your weekly rank? Yeah that's going to change throughout the week and reset each week too

**Comment by panthersdude2001** [comment]
Ok, thats new.

**Comment by panthersdude2001** [comment]
It used to be the max at 50. Now its 200.

**Comment by joeybab3** [comment]
> It used to be the max at 50. Now its 200.

You mean it shows more people now? That's not really an issue lmao just a design choice

**Comment by panthersdude2001** [comment]
Yes it shows more people. Now we know why.

**Comment by panthersdude2001** [comment]
JUST IN: Another sequence down, 10 to go. https://openstreetcam.org/details/2381174

**Comment by panthersdude2001** [comment]
JUST IN, AGAIN: Two more sequences cleared the processing process, now 8 to go. https://openstreetcam.org/details/2381650
https://openstreetcam.org/details/2381658

**Comment by panthersdude2001** [comment]
Four down, four to go! https://openstreetcam.org/details/2385490 https://openstreetcam.org/details/2385494/
https://openstreetcam.org/details/2386098 https://openstreetcam.org/details/2386102/

**Comment by panthersdude2001** [comment]
All sequences from the 15th and the 12th are processed! https://openstreetcam.org/details/2413294 https://openstreetcam.org/details/2413306 https://openstreetcam.org/details/2413334 https://openstreetcam.org/details/2413350

**Comment by panthersdude2001** [comment]
@joeybab3 @chip-grab #244 is causing tracks to be COR-ed out. https://openstreetcam.org/details/2447522

**Comment by joeybab3** [comment]
@panthersdude2001 I'm not seeing this issue on my end. The track you sent above doesn't seem to exist or at least is similar to a track of mine that I deleted but still shows up in my feed. When clicking on this deleted track it shows the same message that I get when I open the one you sent but all of my other tracks load fine. 

Please keep discussion of other errors to the associated threads though it makes getting and giving help on GitHub much easier when you don't have to scroll through a crap ton of comments.

**Comment by panthersdude2001** [comment]
Ok, Try this one, https://openstreetcam.org/details/2447310/0/track-info
It is processing right now, so if it doesnt work, check back in a few minutes.

**Comment by panthersdude2001** [comment]
> Please keep discussion of other errors to the associated threads though it makes getting and giving help on GitHub much easier when you don't have to scroll through a crap ton of comments.

Since the #244 bug has to do with processing, and the PPR (Proccessing PipeLine Rebuild), this is related,

**Comment by panthersdude2001** [comment]
Ok, I get your point @joeybab3, I will move all my posts to a new issue.
