### ISSUE TITLE
No street address origin for MD 2.0?

### ISSUE THREAD

**Issue by panthersdude2001** [openstreetcam/openstreetcam.org#257]
Well, we have another problem with MD 2.0. It seems to be the location thingy at the bottom of the sequence is gone. Is this going to be fixed, or is this a part of MD 2.0?
Mapillary also had this too.
Oh, and by the way, thanks for placing the mapillary sequences back on nearby tracks! I had a ton of those when going up north for my uncle's funeral.
![image](https://user-images.githubusercontent.com/44646536/85056875-f64cc780-b16d-11ea-8b70-3a2997502ab7.png)
Thanks

**Comment by panthersdude2001** [comment]
Lookie loo! We have @chip-grab placing bug! Yay!

**Comment by chip-grab** [comment]
@panthersdude2001, reverse geocoding was deactivated. It will be back with the refactored pipeline. 🤞

**Comment by panthersdude2001** [comment]
Excellent.

**Comment by panthersdude2001** [comment]
Closing as the PPR is complete.
