### ISSUE TITLE
Form filed error on drivers.openstreetcam.org

### ISSUE THREAD

**Issue by abdhessuk** [openstreetcam/openstreetcam.org#260]
I can't choose a Country when i'm trying to register. The only country available on the form is Malaysia. Could you fix that issue please?

**Comment by abdhessuk** [comment]
![2020-06-21_20-24](https://user-images.githubusercontent.com/32804877/85232156-944dc580-b3ec-11ea-9aea-37c753168790.png)
I have no way to change the country field

**Comment by chip-grab** [comment]
@abdhessuk, drivers campaign are no longer available. Will update the website, thanks for highlighting this.
