### ISSUE TITLE
openstreetmap.org authentication doesn't work anymore

### ISSUE THREAD

**Issue by turion** [openstreetcam/openstreetcam.org#261]
I tried to log in with openstreetmap.org, but I couldn't get it to work. I get to the callback (`https://www.openstreetmap.org/oauth/authorize?oauth_callback=https%3A%2F%2Fopenstreetcam.org%2Fauth%2Fopenstreetmap&oauth_token=blablabla`) and I can click the authorization button there, but then I get back to openstreetcam which informs me that `Ups! Authentication failed!`

**Comment by panthersdude2001** [comment]
Same here, but a different message. Logging in to OSC using google and going to sequences doesnt work anymore. It just says loading profile data.

**Comment by joeybab3** [comment]
I can add a +1 to this, on a browser where I was already logged in it is still logged in but I can't log in anywhere else that wasn't previously signed in.

**Comment by panthersdude2001** [comment]
> I can add a +1 to this, on a browser where I was already logged in it is still logged in but I can't log in anywhere else that wasn't previously signed in.

Did it for you. 😎

**Comment by panthersdude2001** [comment]
And now, it seems to be for me now. OSC does not want to sign in properly with BOTH OSM and Google. Only solution is to clear cache ATTM.

**Comment by chip-grab** [comment]
@turion, login is now fixed, please try again.

**Comment by panthersdude2001** [comment]
good.
  ----- Original Message -----

**Comment by turion** [comment]
Great! I can confirm this issue is resolved.
