### ISSUE TITLE
10 points for every image now?

### ISSUE THREAD

**Issue by joeybab3** [openstreetcam/openstreetcam.org#295]
Every image just says it is 0 coverage despite in some cases being covered 10+ times now. 
I guess this is a slight improvement over 0 points for every track but I don't know if this is intended either.
OBD still doesn't register (only on the website, apparently it works on mobile?).
https://openstreetcam.org/details/3112926/184/track-info

I am still losing 25-50% of my tracks each upload and the lack of any meaningful dialogue from the maintainers of this project continues to disappoint me.

**Comment by thatoneiowan** [comment]
I had the same problem but it appears to have been resolved.

**Comment by joeybab3** [comment]
Seems to have been fixed
