### ISSUE TITLE
Action camera uploads create jagged trace

### ISSUE THREAD

**Issue by mvexel** [openstreetcam/openstreetcam.org#4]
Example: 

http://openstreetview.org/details/10139/0

<img width="1492" alt="screenshot 2016-07-21 16 10 46" src="https://cloud.githubusercontent.com/assets/120452/17040578/b9632de4-4f5d-11e6-93eb-3bb634c04f47.png">

**Comment by james2432** [comment]
might be due to the rounding issue with the python script, the gps coordinates were rounded to 4 decimal places which can cause up to 11m error at equator. They've fixed the python script, not sure if you reprocessed the older data

**Comment by mirunac-telenav** [comment]
Fixed.
