### ISSUE TITLE
OSM attribution

### ISSUE THREAD

**Issue by porjo** [openstreetcam/openstreetcam.org#56]
The current attribution panel displays like this:
![screenshot from 2016-08-22 07-55-48](https://cloud.githubusercontent.com/assets/1296987/17840007/f3b91f0a-683d-11e6-89bc-6fc70f31328d.png)

It's not clear that this is a license attribution. IMHO it'd be better to provide an attribution like `© OpenStreetMap contributors`, perhaps with a bit more left/right margin to separate it from 'Scout' and 'Leaflet'

**Comment by cquest** [comment]
I was about to create the same new issue ;)

**Comment by scruss** [comment]
Absolutely. This is what OSM requests in their Legal FAQ: [Our requested attribution is &quot;© OpenStreetMap contributors&quot;.](http://wiki.openstreetmap.org/wiki/Legal_FAQ#3a._I_would_like_to_use_OpenStreetMap_maps._How_should_I_credit_you.3F "Our requested attribution is &quot;© OpenStreetMap contributors&quot;.")

**Comment by jojo4u** [comment]
It's not absolutely necessary:
_Because OpenStreetMap is its contributors, you may omit the word "contributors" if space is limited._ 
http://wiki.osmfoundation.org/wiki/Licence/Licence_and_Legal_FAQ#How_should_I_attribute_you.3F

**Comment by scruss** [comment]
One shouldn't omit the ©, though

**Comment by porjo** [comment]
Just checked site and this is fixed
