### ISSUE TITLE
Strange track.

### ISSUE THREAD

**Issue by bezuglov3000** [openstreetcam/openstreetcam.org#77]
I found track http://openstreetview.org/details/11175/3334

Gps position isn't correct on the full time of track was writen. Maybe starting shots are correct. I think user's video and tracker have been sinchronized, but something went wrong.

**Comment by bogdans-telenav** [comment]
@bezuglov3000 this is caused by a bug in the upload scripts that scrambled the data recorded. This was fixed a long time ago.
